# Generated by Django 3.0.4 on 2020-03-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='description',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='hire_date',
            new_name='join_date',
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='google',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='landline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
